Name=Egg Viper
Author=Speeps, Woofmute, Exant
Version=1.1b
GameVersions=610-7029  V1.00019981016
Description=Makes Egg Viper bootable. Platforms have no collision as they're missing calls to RegisterCollisionEntry.'
ReplacePointers=B_EGM3.PRS

[B_EGM3.PRS]

;EGM3 hijack platform init returns branch
;500a=23a0
;EGM3 ColHijack code
;5054=2dd10b4109000da00900
;EGM3Col code
;2f024=d3670877eb56fc766227e36501d12b4101d4

;pointer for EGM3Col
;510c,be=0c92f024
;pointer for RegisterCollisionEntry
;2f038,be=8c046e20
;Col Flags
;2f03c=00000008

;32ascii prs name
2d03c,be=8c50ab74