Name=Chaos 0
Author=Speeps, woofmute
Version=1.3
GameVersions=610-7029  V1.00019981016
Description=Makes Chaos 0 bootable in the Autodemo.
ReplacePointers=B_CHAOS0.PRS

[B_CHAOS0.PRS]
;CHAOS0_OBJECT prs name
;6230,be=8c5abbb4
;32ascii.pvr texlist
624c,be=8c50ab74
;TIKAL prs name
6250,be=8c127abc
;CHAOS_SURFACE prs name
;6258,be=8c5abbb8
;CHAOS0 prs name
;6268,be=8c5abbb0
;CHAOS0 rain prs name
;6270,be=8c5abbbc
;EFF_REGULAR prs name
;6278,be=8c127a04