Name=Hiyoko Colors
Author=MainJP
Version=0.1
GameVersions=610-7029  V1.00019981016
Description=Uses njDrawObject for Hiyoko rendering to restore model colors.

[1ST_READ.BIN]
; EnemyHiyokoDraw
0BACB0=B2 DE 5F 8C

; Hiyoko draw routine
0BB210=B2 DE 5F 8C

; Hiyoko draw routine
0BB720=B2 DE 5F 8C

; EnemyHiyokoBombDraw
0BBE74=B2 DE 5F 8C