Name=Egg Hornet
Author=Speeps, woofmute
Version=1.1
GameVersions=610-7029  V1.00019981016
Description=Makes Egg Hornet bootable.
ReplacePointers=B_EGM1.PRS

[B_EGM1.PRS]
;32ascii prs name
3448,be=8c50ab74