copy PL_TEST.bin gdroot\PL1A0B.BIN
copy PL_TEST.bin gdroot\PL1B0B.BIN
copy PL_TEST.bin gdroot\PL1C0B.BIN
copy PL_TEST.bin gdroot\PL1D0B.BIN
copy PL_TEST.bin gdroot\PL1D1B.BIN
copy PL_TEST.bin gdroot\PL1E0B.BIN
copy PL_TEST.bin gdroot\PL1E1B.BIN
copy PL_TEST.bin gdroot\PL1E2B.BIN
copy PL_TEST.bin gdroot\PL1F0B.BIN
copy PL_TEST.bin gdroot\PL1F1B.BIN
copy PL_TEST.bin gdroot\PL1F2B.BIN
copy PL_TEST.bin gdroot\PL1G0B.BIN
copy PL_TEST.bin gdroot\PL1G1B.BIN
copy PL_TEST.bin gdroot\PL_10B.BIN
copy PL_TEST.bin gdroot\PL_20B.BIN
copy PL_TEST.bin gdroot\PL_21B.BIN
copy PL_TEST.bin gdroot\PL_22B.BIN
copy PL_TEST.bin gdroot\PL_30B.BIN
copy PL_TEST.bin gdroot\PL_31B.BIN
copy PL_TEST.bin gdroot\PL_32B.BIN
copy PL_TEST.bin gdroot\PL_40B.BIN
copy PL_TEST.bin gdroot\PL_40X.BIN
copy PL_TEST.bin gdroot\PL_41B.BIN
copy PL_TEST.bin gdroot\PL_41X.BIN
copy PL_TEST.bin gdroot\PL_42B.BIN
copy PL_TEST.bin gdroot\PL_50B.BIN
copy PL_TEST.bin gdroot\PL_51B.BIN
copy PL_TEST.bin gdroot\PL_52B.BIN
copy PL_TEST.bin gdroot\PL_60B.BIN
copy PL_TEST.bin gdroot\PL_61B.BIN
copy PL_TEST.bin gdroot\PL_70B.BIN
copy PL_TEST.bin gdroot\PL_71B.BIN
copy PL_TEST.bin gdroot\PL_80B.BIN
copy PL_TEST.bin gdroot\PL_81B.BIN
copy PL_TEST.bin gdroot\PL_82B.BIN
copy PL_TEST.bin gdroot\PL_83B.BIN
copy PL_TEST.bin gdroot\PL_90B.BIN
copy PL_TEST.bin gdroot\PL_90X.BIN
copy PL_TEST.bin gdroot\PL_91B.BIN
copy PL_TEST.bin gdroot\PL_92B.BIN
copy PL_TEST.bin gdroot\PL_93B.BIN
copy PL_TEST.bin gdroot\PL_9MB.BIN
copy PL_TEST.bin gdroot\PL_A0B.BIN
copy PL_TEST.bin gdroot\PL_A0X.BIN
copy PL_TEST.bin gdroot\PL_A1B.BIN
copy PL_TEST.bin gdroot\PL_A2B.BIN
copy PL_TEST.bin gdroot\PL_A2X.BIN
copy PL_TEST.bin gdroot\PL_C0B.BIN
copy PL_TEST.bin gdroot\PL_C1B.BIN
copy PL_TEST.bin gdroot\PL_C2B.BIN
copy PL_TEST.bin gdroot\PL_F0B.BIN
copy PL_TEST.bin gdroot\PL_G0B.BIN
copy PL_TEST.bin gdroot\PL_G0X.BIN
copy PL_TEST.bin gdroot\PL_H0B.BIN
copy PL_TEST.bin gdroot\PL_I0B.BIN
copy PL_TEST.bin gdroot\PL_J0B.BIN
copy PL_TEST.bin gdroot\PL_J1B.BIN
copy PL_TEST.bin gdroot\PL_K0B.BIN
copy PL_TEST.bin gdroot\PL_M0B.BIN
copy PL_TEST.bin gdroot\PL_M0X.BIN
copy PL_TEST.bin gdroot\PL_MRD.BIN
copy PL_TEST.bin gdroot\PL_MRE.BIN
copy PL_TEST.bin gdroot\PL_MRN.BIN
copy PL_TEST.bin gdroot\PL_N0B.BIN
copy PL_TEST.bin gdroot\PL_O0B.BIN
copy PL_TEST.bin gdroot\PL_P0B.BIN
copy PL_TEST.bin gdroot\PL_Q0B.BIN
copy PL_TEST.bin gdroot\PL_Q1B.BIN
copy PL_TEST.bin gdroot\PL_Q2B.BIN
copy PL_TEST.bin gdroot\PL_Q3B.BIN
copy PL_TEST.bin gdroot\PL_Q4B.BIN
copy PL_TEST.bin gdroot\PL_Q5B.BIN
copy PL_TEST.bin gdroot\PL_T0B.BIN
copy PL_TEST.bin gdroot\PL_T1B.BIN
copy PL_TEST.bin gdroot\PL_T2B.BIN
copy PL_TEST.bin gdroot\PL_T3B.BIN
copy PL_TEST.bin gdroot\PL_T4B.BIN
copy PL_TEST.bin gdroot\PL_T5B.BIN
copy PL_TEST.bin gdroot\PL_W0B.BIN
copy PL_TEST.bin gdroot\PL_W1B.BIN
copy PL_TEST.bin gdroot\PL_W2B.BIN
copy PL_TEST.bin gdroot\PL_W3B.BIN
copy PL_TEST.bin gdroot\PL_W4B.BIN
copy PL_TEST.bin gdroot\PL_W5B.BIN
copy PL_TEST.bin gdroot\PL_X0B.BIN
copy PL_TEST.bin gdroot\PL_X1B.BIN
copy PL_TEST.bin gdroot\PL_X2B.BIN
copy PL_TEST.bin gdroot\PL_X3B.BIN
copy PL_TEST.bin gdroot\PL_Y0B.BIN
copy PL_TEST.bin gdroot\PL_Y1B.BIN
copy PL_TEST.bin gdroot\PL_Y2B.BIN
copy PL_TEST.bin gdroot\PL_Z0B.BIN
copy SL_TEST.bin gdroot\SL1A0B.BIN
copy SL_TEST.bin gdroot\SL1B0B.BIN
copy SL_TEST.bin gdroot\SL1C0B.BIN
copy SL_TEST.bin gdroot\SL1D0B.BIN
copy SL_TEST.bin gdroot\SL1D1B.BIN
copy SL_TEST.bin gdroot\SL1E0B.BIN
copy SL_TEST.bin gdroot\SL1E1B.BIN
copy SL_TEST.bin gdroot\SL1E2B.BIN
copy SL_TEST.bin gdroot\SL1F0B.BIN
copy SL_TEST.bin gdroot\SL1F1B.BIN
copy SL_TEST.bin gdroot\SL1F2B.BIN
copy SL_TEST.bin gdroot\SL1G0B.BIN
copy SL_TEST.bin gdroot\SL1G1B.BIN
copy SL_TEST.bin gdroot\SL_10B.BIN
copy SL_TEST.bin gdroot\SL_20B.BIN
copy SL_TEST.bin gdroot\SL_21B.BIN
copy SL_TEST.bin gdroot\SL_22B.BIN
copy SL_TEST.bin gdroot\SL_30B.BIN
copy SL_TEST.bin gdroot\SL_31B.BIN
copy SL_TEST.bin gdroot\SL_32B.BIN
copy SL_TEST.bin gdroot\SL_40B.BIN
copy SL_TEST.bin gdroot\SL_40X.BIN
copy SL_TEST.bin gdroot\SL_41B.BIN
copy SL_TEST.bin gdroot\SL_41X.BIN
copy SL_TEST.bin gdroot\SL_42B.BIN
copy SL_TEST.bin gdroot\SL_50B.BIN
copy SL_TEST.bin gdroot\SL_51B.BIN
copy SL_TEST.bin gdroot\SL_52B.BIN
copy SL_TEST.bin gdroot\SL_60B.BIN
copy SL_TEST.bin gdroot\SL_61B.BIN
copy SL_TEST.bin gdroot\SL_70B.BIN
copy SL_TEST.bin gdroot\SL_71B.BIN
copy SL_TEST.bin gdroot\SL_80B.BIN
copy SL_TEST.bin gdroot\SL_81B.BIN
copy SL_TEST.bin gdroot\SL_82B.BIN
copy SL_TEST.bin gdroot\SL_83B.BIN
copy SL_TEST.bin gdroot\SL_90B.BIN
copy SL_TEST.bin gdroot\SL_90X.BIN
copy SL_TEST.bin gdroot\SL_91B.BIN
copy SL_TEST.bin gdroot\SL_92B.BIN
copy SL_TEST.bin gdroot\SL_93B.BIN
copy SL_TEST.bin gdroot\SL_9MB.BIN
copy SL_TEST.bin gdroot\SL_A0B.BIN
copy SL_TEST.bin gdroot\SL_A0X.BIN
copy SL_TEST.bin gdroot\SL_A1B.BIN
copy SL_TEST.bin gdroot\SL_A2B.BIN
copy SL_TEST.bin gdroot\SL_A2X.BIN
copy SL_TEST.bin gdroot\SL_C0B.BIN
copy SL_TEST.bin gdroot\SL_C1B.BIN
copy SL_TEST.bin gdroot\SL_C2B.BIN
copy SL_TEST.bin gdroot\SL_F0B.BIN
copy SL_TEST.bin gdroot\SL_G0B.BIN
copy SL_TEST.bin gdroot\SL_G0X.BIN
copy SL_TEST.bin gdroot\SL_H0B.BIN
copy SL_TEST.bin gdroot\SL_I0B.BIN
copy SL_TEST.bin gdroot\SL_J0B.BIN
copy SL_TEST.bin gdroot\SL_J1B.BIN
copy SL_TEST.bin gdroot\SL_K0B.BIN
copy SL_TEST.bin gdroot\SL_M0B.BIN
copy SL_TEST.bin gdroot\SL_M0X.BIN
copy SL_TEST.bin gdroot\SL_MRD.BIN
copy SL_TEST.bin gdroot\SL_MRE.BIN
copy SL_TEST.bin gdroot\SL_MRN.BIN
copy SL_TEST.bin gdroot\SL_N0B.BIN
copy SL_TEST.bin gdroot\SL_O0B.BIN
copy SL_TEST.bin gdroot\SL_P0B.BIN
copy SL_TEST.bin gdroot\SL_Q0B.BIN
copy SL_TEST.bin gdroot\SL_Q1B.BIN
copy SL_TEST.bin gdroot\SL_Q2B.BIN
copy SL_TEST.bin gdroot\SL_Q3B.BIN
copy SL_TEST.bin gdroot\SL_Q4B.BIN
copy SL_TEST.bin gdroot\SL_Q5B.BIN
copy SL_TEST.bin gdroot\SL_T0B.BIN
copy SL_TEST.bin gdroot\SL_T1B.BIN
copy SL_TEST.bin gdroot\SL_T2B.BIN
copy SL_TEST.bin gdroot\SL_T3B.BIN
copy SL_TEST.bin gdroot\SL_T4B.BIN
copy SL_TEST.bin gdroot\SL_T5B.BIN
copy SL_TEST.bin gdroot\SL_W0B.BIN
copy SL_TEST.bin gdroot\SL_W1B.BIN
copy SL_TEST.bin gdroot\SL_W2B.BIN
copy SL_TEST.bin gdroot\SL_W3B.BIN
copy SL_TEST.bin gdroot\SL_W4B.BIN
copy SL_TEST.bin gdroot\SL_W5B.BIN
copy SL_TEST.bin gdroot\SL_X0B.BIN
copy SL_TEST.bin gdroot\SL_X1B.BIN
copy SL_TEST.bin gdroot\SL_X2B.BIN
copy SL_TEST.bin gdroot\SL_X3B.BIN
copy SL_TEST.bin gdroot\SL_Y0B.BIN
copy SL_TEST.bin gdroot\SL_Y1B.BIN
copy SL_TEST.bin gdroot\SL_Y2B.BIN
copy SL_TEST.bin gdroot\SL_Z0B.BIN